"""
test_skill_first_rule - R36 is written where every harness reads it.

Offline, reads documentation only. Nothing here touches the vault, the graph or
any live configuration.

Why it exists. R36 says no task runs without a skill or an agent that uses one,
and that a missing skill is authored in ResearchTools and never installed from
the internet. A rule that lives in one file is invisible to the harnesses that
read another, and a documented claim with no test reads as verified by the next
session (R15). This suite fails when the rule disappears from the source
(`.claude/CLAUDE.md`, inside the exported region), from the generated contract in
`CLAUDE.template.md`, from `workflows.md` and `security.md`, from the three
mirrors `install.ps1` writes, or from the rule index.

Scope, stated rather than hidden: it proves the rule is WRITTEN in each place. It
cannot prove that a model obeyed it. Each check has its negative control on a
fixture, since a finder that cannot fail proves nothing (R20).
"""
import tempfile
import unittest
from pathlib import Path
from typing import Iterable

REPO = Path(__file__).resolve().parents[3]

# R6: the phrases are data. Each one is the load-bearing clause of one part of R36.
# Renumbered from R34 to R36 2026-10-06: R34/R35 collided with PR #40's privacy-guard
# rules, further along and closer to merge; this branch's own two rules moved instead.
CORE_PHRASES = (
    "R36",
    "AskUserQuestion",
    "skill-creator",
    "find-skills",
    "Never install a skill from the internet",
)

# Mirrors generated by install.ps1 carry a shorter statement of the same rule.
# "ad hoc" + "enabledPlugins" is the 2026-10-06 fix for the Copilot finding that this
# shorter statement banned the plugin the repo's own template approves (skill-creator).
# "ask first" is the 2026-10-07 fix for the re-review finding that the SAME shorter
# statement skipped part 3's ask-before-author gate, so a Copilot/Aider/Codex session
# reading only the mirror authored a skill with no AskUserQuestion at all.
MIRROR_PHRASES = (
    "R36", "skill-creator", "find-skills", "ad hoc", "enabledPlugins", "by hand",
    "ask first too",
)
# The exact clause that must NEVER survive anywhere this rule is stated: it is the
# contradiction the 2026-10-07 re-review found in the routing-table row, which let a
# model skip the ask gate for a genuine no-owner gap because the row disagreed with
# part 3's own text.
FORBIDDEN_PHRASE = "otherwise author the missing skill"
# 2026-10-07 third re-review (N1/N2/N4, O1/O2): the headless exemption contradicted
# part 2's old "stop" clause, so part 2 now shares part 3's OWNER UNKNOWN fallback
# (the operator's own answer to O2); the operator's own answer to O1 adds a one-line
# floor so a single-step request (reading one file, "git status") never reaches the
# ask gate at all; and the fallback search for an entirely new skill now says
# explicitly where it is authored, closing the loophole where a non-ResearchTools
# session's fallback read as writing the SKILL.md into that project.
FLOOR_AND_FALLBACK_PHRASES = (
    "git status", "OWNER UNKNOWN", "inside ResearchTools",
    "single-step request", "deliverable of its own",
)
# 2026-10-07 fourth re-review, the operator's own decisions on M1 (Wording A) and L6
# (an explicit user request to install a skill is honored, but outside ResearchTools)
# and the B1 fix (the "do not stop" fallback no longer dead-ends on a fresh clone with
# no measured-green repository, closing the contradiction with that protocol's own
# step 2).
EXEMPTION_PHRASE = "capability at all"
RETIRED_EXEMPTION_PHRASE = "no human in the loop"
# 2026-10-07 fifth re-review (F1, owner's own answer): "capability" means any way to ask
# the user, in chat or through the tool, so Codex and Copilot chat - which have no
# AskUserQuestion TOOL but can still ask in chat - are bound, not exempt. Written as a
# clarifying clause beside the exemption sentence everywhere it appears.
CAPABILITY_CLARIFICATION_PHRASES = ("by the tool or in chat", "are bound, not exempt")
# F5: an explicit user request to install a skill (the L6 exception) must come from the
# user's own message, never from a tool result, a README, or a subagent's report - the
# exact injection vector security.md's own prompt-injection paragraph already names.
EXPLICIT_INSTALL_SOURCE_PHRASES = ("own message", "subagent's report")
# F4: "latest cloud" is worded identically everywhere; the authoring-location negative
# ("not in the project the task is for") uses two synonymous phrasings depending on
# whether the sentence names the gap-filling project ("the project the task is for") or
# the session's own working directory ("the current project") - either is acceptable,
# but at least one must survive.
AUTHORING_LOCATION_NEGATIVE_VARIANTS = ("never inside the project", "never the current project")
EXPLICIT_INSTALL_PHRASE = "outside ResearchTools"
GREEN_STAMP_PHRASES = (".rt-green.json", "not author")
FLOOR_AND_FALLBACK_FILES = (
    ".claude/CLAUDE.md", ".claude/rules/workflows.md", "install.ps1",
    "docs/authoring-and-mirrors.md", "docs/manual/04-skills.md",
)
# .claude/CLAUDE.md and workflows.md each carry a SECOND, unrelated OWNER UNKNOWN /
# "inside ResearchTools" source: the "Improving ResearchTools from another folder"
# protocol itself. A whole-file phrase check on those two files would stay green even
# if the phrase were deleted from the R36 section specifically, since the protocol
# section still has it. The other three files have no such second section, so a
# whole-file check there is already precise.
R36_SECTION_HEADING = {
    ".claude/CLAUDE.md": "## Skill-first rule (R36)",
    ".claude/rules/workflows.md": "## Skill-first execution",
    "CLAUDE.template.md": "## Skill-first rule (R36)",
}

# The generator holds one heredoc per mirror, so the phrases must occur once for each.
INSTALLER = "install.ps1"
INSTALLER_HEREDOCS = 3
MIRRORS = ("AGENTS.md", "CONVENTIONS.md", ".github/copilot-instructions.md")

EXPORT_BEGIN, EXPORT_END = "<!-- RT-EXPORT:BEGIN -->", "<!-- RT-EXPORT:END -->"
CONTRACT_BEGIN, CONTRACT_END = "<!-- RT-CONTRACT:BEGIN -->", "<!-- RT-CONTRACT:END -->"


def region(text: str, begin: str, end: str) -> str:
    """
    --------------------------------------------------------------------------
    Purpose:
        Return the text between two markers, or an empty string when either
        marker is absent or they are reversed.

    Inputs:
        text (str): the whole file.
        begin (str): the opening marker.
        end (str): the closing marker.

    Outputs:
        body (str): the text strictly between the markers, possibly empty.
    --------------------------------------------------------------------------
    """
    start = text.find(begin)
    stop = text.find(end)
    if start < 0 or stop < 0 or stop < start:
        return ""
    return text[start + len(begin):stop]


def flat_section_text(whole: str, heading: str | None) -> str:
    """
    --------------------------------------------------------------------------
    Purpose:
        Pure text logic behind `flat_section`: narrow `whole` to the body
        following `heading` up to the next top-level heading (or the end),
        then fold hard-wrapped line breaks to single spaces so a phrase split
        across a line is still found. Separated from `flat_section` so this
        logic is testable (R20) without touching the repository's own files.

    Inputs:
        whole (str): the full text of one file.
        heading (str or None): the section marker to narrow to, or None to
            flatten the whole text unchanged (a file with no second,
            unrelated source of the same phrases).

    Outputs:
        text (str): the narrowed, flattened text, possibly empty when
            `heading` is given but not found.
    --------------------------------------------------------------------------
    """
    if heading is None:
        return " ".join(whole.split())
    start = whole.find(heading)
    if start < 0:
        return ""
    rest = whole[start + len(heading):]
    stop = rest.find("\n## ")
    body = rest if stop < 0 else rest[:stop]
    return " ".join(body.split())


def flat_section(rel: str) -> str:
    """
    --------------------------------------------------------------------------
    Purpose:
        Return the R36 section of one repository file, narrowed and
        flattened by `flat_section_text`, so a phrase check cannot pass by
        matching an unrelated section of a file that also discusses OWNER
        UNKNOWN or ResearchTools (the "Improving ResearchTools from another
        folder" protocol, in particular).

    Inputs:
        rel (str): path relative to the repository root, a key of
            R36_SECTION_HEADING when the file carries more than one such
            mention, or any other file otherwise.

    Outputs:
        text (str): the narrowed text to search, flattened to single spaces.
    --------------------------------------------------------------------------
    """
    return flat_section_text(read(rel), R36_SECTION_HEADING.get(rel))


def missing(text: str, phrases: Iterable[str]) -> list[str]:
    """
    --------------------------------------------------------------------------
    Purpose:
        List the phrases a text does not contain.

    Inputs:
        text (str): the text searched.
        phrases (iterable of str): the phrases required.

    Outputs:
        absent (list of str): the phrases not found, in the order given.
    --------------------------------------------------------------------------
    """
    return [p for p in phrases if p not in text]


def read(rel: str) -> str:
    """
    --------------------------------------------------------------------------
    Purpose:
        Read one repository file as utf-8.

    Inputs:
        rel (str): path relative to the repository root.

    Outputs:
        text (str): the file content.

    Raises:
        FileNotFoundError: the file is absent, which is itself a failure here.
    --------------------------------------------------------------------------
    """
    return (REPO / rel).read_text(encoding="utf-8")


class TestRuleIsWritten(unittest.TestCase):
    def test_source_exports_the_rule(self):
        body = region(read(".claude/CLAUDE.md"), EXPORT_BEGIN, EXPORT_END)
        self.assertTrue(body, "RT-EXPORT region not found in .claude/CLAUDE.md")
        self.assertEqual(missing(body, CORE_PHRASES), [])

    def test_template_contract_block_carries_it(self):
        body = region(read("CLAUDE.template.md"), CONTRACT_BEGIN, CONTRACT_END)
        self.assertTrue(body, "RT-CONTRACT block not found in CLAUDE.template.md")
        self.assertEqual(missing(body, CORE_PHRASES), [],
                         "regenerate the block with install.ps1")

    def test_workflows_holds_the_full_rule(self):
        text = read(".claude/rules/workflows.md")
        self.assertIn("**R36 - no task runs without a skill", text)
        self.assertEqual(missing(text, CORE_PHRASES), [])

    def test_security_names_skill_provenance(self):
        text = read(".claude/rules/security.md")
        self.assertIn("## Skill provenance", text)
        self.assertEqual(missing(text, ("skill-creator", "find-skills", "R36")), [])

    def test_rule_index_names_r36(self):
        text = read(".claude/rules/code-style.md")
        self.assertIn("`R0` to `R36`", text)
        self.assertIn("`R36` in `workflows.md`", text)

    def test_every_generated_mirror_states_it(self):
        for rel in MIRRORS:
            with self.subTest(mirror=rel):
                self.assertEqual(missing(read(rel), MIRROR_PHRASES), [],
                                 "regenerate the mirror with install.ps1")

    def test_installer_sources_carry_it_once_per_mirror(self):
        # Mirrors are overwritten at the next install.ps1 run, so the generator is
        # what must hold the rule; a green mirror alone would hide a dropped heredoc.
        text = read(INSTALLER)
        for phrase in MIRROR_PHRASES:
            with self.subTest(phrase=phrase):
                self.assertGreaterEqual(text.count(phrase), INSTALLER_HEREDOCS)

    def test_task_is_the_unit_of_work_not_each_tool_call(self):
        # 2026-10-07 operator correction: "task" had no stated unit, which read as
        # requiring a skill lookup for a bare git status or a single file read. The
        # rule now says a task is the request/goal the session is pursuing, and
        # scopes itself to interactive harnesses, aider-setup's headless pipeline
        # named as the explicit example of what is out of reach.
        for rel in FLOOR_AND_FALLBACK_FILES:
            with self.subTest(file=rel):
                self.assertIn("aider-setup", flat_section(rel))

    def test_exemption_uses_wording_a_everywhere(self):
        # 2026-10-07 fourth re-review (M1): two families of wording for the same
        # exemption had drifted apart ("no AskUserQuestion capability at all" in the
        # full-text files, "no human in the loop" in the mirrors and installer),
        # which let a tool-less-but-human-present harness (Aider chat) and a
        # capability-less subagent read as covered by two different, disagreeing
        # tests. The operator's decision: Wording A everywhere, the old wording
        # retired, so a dropped or reworded exemption in any one copy fails here.
        for rel in FLOOR_AND_FALLBACK_FILES:
            with self.subTest(file=rel):
                flat = flat_section(rel)
                self.assertIn(EXEMPTION_PHRASE, flat)
                self.assertNotIn(RETIRED_EXEMPTION_PHRASE, flat)

    def test_floor_and_owner_unknown_fallback_are_stated(self):
        # 2026-10-07 operator answers to O1 (floor) and O2 (can't-ask-but-not-headless
        # fallback): a single-step request never reaches the ask gate, and a run that
        # cannot ask logs OWNER UNKNOWN and continues rather than stopping (closing N1,
        # the contradiction between the headless exemption and part 2's old "stop").
        for rel in FLOOR_AND_FALLBACK_FILES:
            with self.subTest(file=rel):
                flat = flat_section(rel)
                for phrase in FLOOR_AND_FALLBACK_PHRASES:
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)

    def test_no_file_says_the_work_merely_stops(self):
        # The old part-2 clause this replaces; its survival anywhere would mean the
        # OWNER UNKNOWN fallback above was added beside it rather than instead of it.
        for rel in FLOOR_AND_FALLBACK_FILES:
            with self.subTest(file=rel):
                self.assertNotIn("stop and say so", flat_section(rel))

    def test_fresh_clone_does_not_author_past_a_missing_green_stamp(self):
        # 2026-10-07 fourth re-review (B1): the "skill-creator absent, do not stop"
        # fallback and the 8-step protocol it cites disagreed on a fresh clone, which
        # has no .rt-green.json by construction - the fallback said author anyway, the
        # protocol's own step 2 said report and stop. Fixed by making the green-stamp
        # check govern authoring specifically, independent of whether skill-creator is
        # installed, in every copy.
        for rel in FLOOR_AND_FALLBACK_FILES:
            with self.subTest(file=rel):
                flat = flat_section(rel)
                for phrase in GREEN_STAMP_PHRASES:
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)

    def test_capability_means_chat_or_tool_not_the_tool_alone(self):
        # 2026-10-07 fifth re-review (F1), owner's own answer: a harness with no
        # AskUserQuestion TOOL (Codex, Copilot chat, most subagents) is still bound if it
        # can ask in chat - only a harness with no way to ask AT ALL is exempt. Checked in
        # every file that states the exemption; security.md does not restate the
        # exemption itself, so it is not in this list.
        for rel in FLOOR_AND_FALLBACK_FILES:
            with self.subTest(file=rel):
                flat = flat_section(rel)
                for phrase in CAPABILITY_CLARIFICATION_PHRASES:
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)

    def test_explicit_install_must_come_from_the_users_own_message(self):
        # 2026-10-07 fifth re-review (F5): nothing previously said an "explicit user
        # request" to install a skill had to come from the user, rather than from a tool
        # result, a README, or a subagent's report parroting one - exactly the injection
        # vector security.md's own prompt-injection paragraph already treats as an attack
        # elsewhere in the same file.
        for rel in (*FLOOR_AND_FALLBACK_FILES, ".claude/rules/security.md"):
            with self.subTest(file=rel):
                flat = flat_section(rel)
                for phrase in EXPLICIT_INSTALL_SOURCE_PHRASES:
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)

    def test_latest_cloud_model_and_authoring_location_are_pinned(self):
        # 2026-10-07 fifth re-review (F4): a mutation check found "latest cloud" and the
        # authoring-location negative could be deleted from several copies without
        # failing anything, because nothing asserted them. Pinned here, everywhere.
        for rel in (*FLOOR_AND_FALLBACK_FILES, "CLAUDE.template.md", *MIRRORS):
            with self.subTest(file=rel):
                flat = flat_section(rel)
                self.assertIn("latest cloud", flat)
                self.assertTrue(
                    any(v in flat for v in AUTHORING_LOCATION_NEGATIVE_VARIANTS),
                    f"neither authoring-location variant found in {rel}")

    def test_explicit_user_install_lands_outside_researchtools(self):
        # 2026-10-07 fourth re-review (L6), owner's own answer: part 4's ban is
        # purpose-gated to covering a missing skill ad hoc, not a blanket ban: an
        # explicit user request to install a skill is honored, but the install lands
        # outside ResearchTools, never added to the repository, its mirrors, or its
        # junctions.
        for rel in (*FLOOR_AND_FALLBACK_FILES, ".claude/rules/security.md"):
            with self.subTest(file=rel):
                self.assertIn(EXPLICIT_INSTALL_PHRASE, flat_section(rel))

    def test_template_and_mirrors_carry_the_same_floor_and_exemption(self):
        # 2026-10-07 fourth re-review (M3): the floor, the exemption and the
        # OWNER UNKNOWN fallback were asserted in the source files and install.ps1,
        # but never in CLAUDE.template.md's generated contract block or the three
        # generated mirrors - exactly the files a Copilot/Aider/Continue session
        # actually reads. CLAUDE.template.md needs section-scoping like its source
        # (it embeds the "Improving ResearchTools" protocol too); the three mirrors
        # do not, since they carry only the condensed blurb, checked whole-file.
        for rel in ("CLAUDE.template.md", *MIRRORS):
            with self.subTest(file=rel):
                flat = flat_section(rel)
                self.assertIn(EXEMPTION_PHRASE, flat)
                self.assertNotIn(RETIRED_EXEMPTION_PHRASE, flat)
                self.assertIn("git status", flat)
                self.assertIn("OWNER UNKNOWN", flat)
                self.assertIn(".rt-green.json", flat)
                self.assertIn(EXPLICIT_INSTALL_PHRASE, flat)
                for phrase in CAPABILITY_CLARIFICATION_PHRASES:
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)
                for phrase in EXPLICIT_INSTALL_SOURCE_PHRASES:
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)
                for phrase in ("single-step request", "deliverable of its own"):
                    with self.subTest(phrase=phrase):
                        self.assertIn(phrase, flat)

    def test_missing_skill_fallback_and_approved_plugin_are_stated(self):
        # Copilot review of PR 44: the branch must not dead-end on a harness without
        # skill-creator, and the ban must not contradict the declared plugin.
        for rel in (".claude/CLAUDE.md", ".claude/rules/workflows.md"):
            with self.subTest(file=rel):
                text = read(rel)
                self.assertIn("by hand", text)
                self.assertIn("enabledPlugins", text)
        self.assertIn("enabledPlugins", read(".claude/rules/security.md"))
        self.assertIn("skill-creator@claude-plugins-official", read(".claude/settings.template.json"))

    def test_routing_table_has_the_missing_skill_row(self):
        text = read(".claude/CLAUDE.md")
        row = [line for line in text.splitlines()
               if line.startswith("|") and "no skill or agent covers" in line]
        self.assertEqual(len(row), 1)
        self.assertIn("skill-creator", row[0])
        self.assertIn("find-skills", row[0])
        self.assertIn("AskUserQuestion", row[0])

    def test_no_file_lets_the_row_skip_the_ask_gate(self):
        # 2026-10-07 re-review finding: the routing-table row said "ask ... when it is
        # ambiguous, otherwise author the missing skill", contradicting part 3's own
        # "ask first" for a genuine no-owner gap. Asserted repo-wide, and in the generated
        # mirrors and template contract, so the contradiction cannot reappear in a copy.
        for rel in (".claude/CLAUDE.md", "CLAUDE.template.md", ".claude/rules/workflows.md",
                    "docs/authoring-and-mirrors.md", *MIRRORS):
            with self.subTest(file=rel):
                self.assertNotIn(FORBIDDEN_PHRASE, read(rel))


class TestFinderCanFail(unittest.TestCase):
    """R20: each check above must be able to say no."""

    def test_missing_markers_give_an_empty_region(self):
        self.assertEqual(region("no markers here", EXPORT_BEGIN, EXPORT_END), "")

    def test_reversed_markers_give_an_empty_region(self):
        self.assertEqual(region(EXPORT_END + "x" + EXPORT_BEGIN, EXPORT_BEGIN, EXPORT_END), "")

    def test_a_region_without_the_rule_reports_every_phrase(self):
        body = region(f"{EXPORT_BEGIN}\nunrelated text\n{EXPORT_END}", EXPORT_BEGIN, EXPORT_END)
        self.assertEqual(missing(body, CORE_PHRASES), list(CORE_PHRASES))

    def test_dropping_one_clause_is_reported_alone(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rules.md"
            path.write_text("R36 AskUserQuestion skill-creator find-skills", encoding="utf-8")
            absent = missing(path.read_text(encoding="utf-8"), CORE_PHRASES)
        self.assertEqual(absent, ["Never install a skill from the internet"])

    def _read_with_redirected_repo(self, rel: str, content: str) -> str:
        """
        --------------------------------------------------------------------------
        Purpose:
            Write `content` at `rel` under a scratch directory, point the
            module-level `REPO` at it, and return what the real `read()`
            function returns - so a negative control exercises the identical
            file-reading path the production checks use (`read(rel)`), not a
            bare string literal. 2026-10-07 fifth re-review (F3): the previous
            version of this control called `path.read_text()` directly, which
            tests Python's `in` and nothing about this suite's own plumbing.

        Inputs:
            rel (str): the repo-relative path a production check would pass
                to `read()`.
            content (str): the fixture text to plant there.

        Outputs:
            text (str): whatever `read(rel)` returns once `REPO` is
                redirected, restored to its real value before returning.
        --------------------------------------------------------------------------
        """
        global REPO
        saved = REPO
        with tempfile.TemporaryDirectory() as tmp:
            REPO = Path(tmp)
            path = REPO / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            try:
                return read(rel)
            finally:
                REPO = saved

    def test_the_forbidden_phrase_check_can_fail(self):
        text = self._read_with_redirected_repo(
            ".claude/CLAUDE.md", "ask when ambiguous, otherwise author the missing skill")
        self.assertIn(FORBIDDEN_PHRASE, text)

    def test_the_stop_clause_check_can_fail(self):
        text = self._read_with_redirected_repo(
            ".claude/rules/workflows.md", "if the question cannot be asked, stop and say so.")
        self.assertIn("stop and say so", text)

    def test_flat_section_text_can_fail_to_find_the_heading(self):
        # R20 for the new helper: an absent heading must give an empty section, not
        # silently fall back to the whole text (which would hide a deleted heading
        # and let every phrase check below it pass by matching something else).
        self.assertEqual(flat_section_text("no heading here", "## Missing"), "")

    def test_flat_section_text_stops_at_the_next_heading(self):
        # The section must not leak into the next one, or a phrase that was moved
        # OUT of the R36 section (into "Improving ResearchTools", say) would still
        # be found and the drift would go undetected.
        whole = "## R36\nfirst clause\n## Next\nOWNER UNKNOWN lives here only"
        self.assertNotIn("OWNER UNKNOWN", flat_section_text(whole, "## R36"))

    def test_flat_section_text_folds_hard_wrapped_lines(self):
        self.assertIn("no human in the loop",
                      flat_section_text("no human in the\nloop", None))


if __name__ == "__main__":
    unittest.main()
