"""
test_skill_first_rule - R36 is written where every harness reads it.

Offline, reads documentation only. Nothing here touches the vault, the graph or
any live configuration.

Why it exists. R36 says no task runs without a skill or an agent that uses one,
and that a missing skill is authored in ResearchTools and never installed from
the internet. A rule that lives in one file is invisible to the harnesses that
read another, and a documented claim with no test reads as verified by the next
session (R15). This suite fails when the rule disappears from the source
(`.claude/CLAUDE.md`, inside the exported region), from the generated contract in
`CLAUDE.template.md`, from `workflows.md` and `security.md`, from the three
mirrors `install.ps1` writes, or from the rule index.

Scope, stated rather than hidden: it proves the rule is WRITTEN in each place. It
cannot prove that a model obeyed it. Each check has its negative control on a
fixture, since a finder that cannot fail proves nothing (R20).
"""
import tempfile
import unittest
from pathlib import Path
from typing import Iterable

REPO = Path(__file__).resolve().parents[3]

# R6: the phrases are data. Each one is the load-bearing clause of one part of R36.
# Renumbered from R34 to R36 2026-10-06: R34/R35 collided with PR #40's privacy-guard
# rules, further along and closer to merge; this branch's own two rules moved instead.
CORE_PHRASES = (
    "R36",
    "AskUserQuestion",
    "skill-creator",
    "find-skills",
    "Never install a skill from the internet",
)

# Mirrors generated by install.ps1 carry a shorter statement of the same rule.
# "ad hoc" + "enabledPlugins" is the 2026-10-06 fix for the Copilot finding that this
# shorter statement banned the plugin the repo's own template approves (skill-creator).
# "ask first" is the 2026-10-07 fix for the re-review finding that the SAME shorter
# statement skipped part 3's ask-before-author gate, so a Copilot/Aider/Codex session
# reading only the mirror authored a skill with no AskUserQuestion at all.
MIRROR_PHRASES = (
    "R36", "skill-creator", "find-skills", "ad hoc", "enabledPlugins", "by hand",
    "ask first too",
)
# The exact clause that must NEVER survive anywhere this rule is stated: it is the
# contradiction the 2026-10-07 re-review found in the routing-table row, which let a
# model skip the ask gate for a genuine no-owner gap because the row disagreed with
# part 3's own text.
FORBIDDEN_PHRASE = "otherwise author the missing skill"
# The generator holds one heredoc per mirror, so the phrases must occur once for each.
INSTALLER = "install.ps1"
INSTALLER_HEREDOCS = 3
MIRRORS = ("AGENTS.md", "CONVENTIONS.md", ".github/copilot-instructions.md")

EXPORT_BEGIN, EXPORT_END = "<!-- RT-EXPORT:BEGIN -->", "<!-- RT-EXPORT:END -->"
CONTRACT_BEGIN, CONTRACT_END = "<!-- RT-CONTRACT:BEGIN -->", "<!-- RT-CONTRACT:END -->"


def region(text: str, begin: str, end: str) -> str:
    """
    --------------------------------------------------------------------------
    Purpose:
        Return the text between two markers, or an empty string when either
        marker is absent or they are reversed.

    Inputs:
        text (str): the whole file.
        begin (str): the opening marker.
        end (str): the closing marker.

    Outputs:
        body (str): the text strictly between the markers, possibly empty.
    --------------------------------------------------------------------------
    """
    start = text.find(begin)
    stop = text.find(end)
    if start < 0 or stop < 0 or stop < start:
        return ""
    return text[start + len(begin):stop]


def missing(text: str, phrases: Iterable[str]) -> list[str]:
    """
    --------------------------------------------------------------------------
    Purpose:
        List the phrases a text does not contain.

    Inputs:
        text (str): the text searched.
        phrases (iterable of str): the phrases required.

    Outputs:
        absent (list of str): the phrases not found, in the order given.
    --------------------------------------------------------------------------
    """
    return [p for p in phrases if p not in text]


def read(rel: str) -> str:
    """
    --------------------------------------------------------------------------
    Purpose:
        Read one repository file as utf-8.

    Inputs:
        rel (str): path relative to the repository root.

    Outputs:
        text (str): the file content.

    Raises:
        FileNotFoundError: the file is absent, which is itself a failure here.
    --------------------------------------------------------------------------
    """
    return (REPO / rel).read_text(encoding="utf-8")


class TestRuleIsWritten(unittest.TestCase):
    def test_source_exports_the_rule(self):
        body = region(read(".claude/CLAUDE.md"), EXPORT_BEGIN, EXPORT_END)
        self.assertTrue(body, "RT-EXPORT region not found in .claude/CLAUDE.md")
        self.assertEqual(missing(body, CORE_PHRASES), [])

    def test_template_contract_block_carries_it(self):
        body = region(read("CLAUDE.template.md"), CONTRACT_BEGIN, CONTRACT_END)
        self.assertTrue(body, "RT-CONTRACT block not found in CLAUDE.template.md")
        self.assertEqual(missing(body, CORE_PHRASES), [],
                         "regenerate the block with install.ps1")

    def test_workflows_holds_the_full_rule(self):
        text = read(".claude/rules/workflows.md")
        self.assertIn("**R36 - no task runs without a skill", text)
        self.assertEqual(missing(text, CORE_PHRASES), [])

    def test_security_names_skill_provenance(self):
        text = read(".claude/rules/security.md")
        self.assertIn("## Skill provenance", text)
        self.assertEqual(missing(text, ("skill-creator", "find-skills", "R36")), [])

    def test_rule_index_names_r36(self):
        text = read(".claude/rules/code-style.md")
        self.assertIn("`R0` to `R36`", text)
        self.assertIn("`R36` in `workflows.md`", text)

    def test_every_generated_mirror_states_it(self):
        for rel in MIRRORS:
            with self.subTest(mirror=rel):
                self.assertEqual(missing(read(rel), MIRROR_PHRASES), [],
                                 "regenerate the mirror with install.ps1")

    def test_installer_sources_carry_it_once_per_mirror(self):
        # Mirrors are overwritten at the next install.ps1 run, so the generator is
        # what must hold the rule; a green mirror alone would hide a dropped heredoc.
        text = read(INSTALLER)
        for phrase in MIRROR_PHRASES:
            with self.subTest(phrase=phrase):
                self.assertGreaterEqual(text.count(phrase), INSTALLER_HEREDOCS)

    def test_task_is_the_unit_of_work_not_each_tool_call(self):
        # 2026-10-07 operator correction: "task" had no stated unit, which read as
        # requiring a skill lookup for a bare git status or a single file read. The
        # rule now says a task is the request/goal the session is pursuing, and
        # scopes itself to interactive harnesses, aider-setup's headless pipeline
        # named as the explicit example of what is out of reach.
        for rel in (".claude/CLAUDE.md", ".claude/rules/workflows.md",
                    "install.ps1", "docs/authoring-and-mirrors.md"):
            with self.subTest(file=rel):
                # Hard-wrapped prose can split a phrase across a line break, so the
                # check is done on text with newlines folded to spaces, not the raw file.
                flat = " ".join(read(rel).split())
                self.assertIn("no human in the loop", flat)
                self.assertIn("aider-setup", flat)

    def test_missing_skill_fallback_and_approved_plugin_are_stated(self):
        # Copilot review of PR 44: the branch must not dead-end on a harness without
        # skill-creator, and the ban must not contradict the declared plugin.
        for rel in (".claude/CLAUDE.md", ".claude/rules/workflows.md"):
            with self.subTest(file=rel):
                text = read(rel)
                self.assertIn("by hand", text)
                self.assertIn("enabledPlugins", text)
        self.assertIn("enabledPlugins", read(".claude/rules/security.md"))
        self.assertIn("skill-creator@claude-plugins-official", read(".claude/settings.template.json"))

    def test_routing_table_has_the_missing_skill_row(self):
        text = read(".claude/CLAUDE.md")
        row = [line for line in text.splitlines()
               if line.startswith("|") and "no skill or agent covers" in line]
        self.assertEqual(len(row), 1)
        self.assertIn("skill-creator", row[0])
        self.assertIn("find-skills", row[0])
        self.assertIn("AskUserQuestion", row[0])

    def test_no_file_lets_the_row_skip_the_ask_gate(self):
        # 2026-10-07 re-review finding: the routing-table row said "ask ... when it is
        # ambiguous, otherwise author the missing skill", contradicting part 3's own
        # "ask first" for a genuine no-owner gap. Asserted repo-wide, and in the generated
        # mirrors and template contract, so the contradiction cannot reappear in a copy.
        for rel in (".claude/CLAUDE.md", "CLAUDE.template.md", ".claude/rules/workflows.md",
                    "docs/authoring-and-mirrors.md", *MIRRORS):
            with self.subTest(file=rel):
                self.assertNotIn(FORBIDDEN_PHRASE, read(rel))


class TestFinderCanFail(unittest.TestCase):
    """R20: each check above must be able to say no."""

    def test_missing_markers_give_an_empty_region(self):
        self.assertEqual(region("no markers here", EXPORT_BEGIN, EXPORT_END), "")

    def test_reversed_markers_give_an_empty_region(self):
        self.assertEqual(region(EXPORT_END + "x" + EXPORT_BEGIN, EXPORT_BEGIN, EXPORT_END), "")

    def test_a_region_without_the_rule_reports_every_phrase(self):
        body = region(f"{EXPORT_BEGIN}\nunrelated text\n{EXPORT_END}", EXPORT_BEGIN, EXPORT_END)
        self.assertEqual(missing(body, CORE_PHRASES), list(CORE_PHRASES))

    def test_dropping_one_clause_is_reported_alone(self):
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "rules.md"
            path.write_text("R36 AskUserQuestion skill-creator find-skills", encoding="utf-8")
            absent = missing(path.read_text(encoding="utf-8"), CORE_PHRASES)
        self.assertEqual(absent, ["Never install a skill from the internet"])

    def test_the_forbidden_phrase_check_can_fail(self):
        # A planted copy of the contradiction must be caught, or the check proves nothing.
        self.assertIn(FORBIDDEN_PHRASE, "ask when ambiguous, otherwise author the missing skill")


if __name__ == "__main__":
    unittest.main()
