"""
loop_engineer.py - budget-bounded develop-and-improve loop driver (Agent SDK).

Runs the loop-engineering pipeline for one feature: design -> plan -> branch -> TDD tests ->
code -> comment -> run tests + review -> score -> correct, repeating the
evaluate/correct/rescore sub-cycle until a composite quality gate is met or a hard stop is
hit (budget cap, max iterations, or a no-progress plateau). The best cloud model (Fable 5)
orchestrates and judges; cheaper cloud tiers act; code and comments are generated by the
local-coder / local-writer agents over the Bash bridge. Scoring is delegated to
loop_audit.score (the locked gate contract); the merge to a protected branch is human-gated.

Two entry paths:
  --loop      run the real pipeline through the Claude Agent SDK (needs claude-agent-sdk
              installed, Ollama running with the local models, and the installed review
              plugins). The SDK is imported lazily so this file loads offline.
  --dry-run   drive ONLY the loop-control logic over a sequence of precomputed report JSON
              files. No SDK, no models, no network - used by the offline tests and to sanity
              -check budget / no-progress / regression handling.

Ledger artifacts (loop-audit-compatible names) are written under the run directory:
  PROCESS.md          human-readable todo/checkbox state
  loop-run-log.md     append-only per-iteration score + cost
  loop-budget.md      running spend vs the cap
"""

import argparse
import json
import logging
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
import loop_audit  # noqa: E402  (sibling module; the locked scorer/gate)

logger = logging.getLogger(__name__)

# Model tiering: the best model judges, cheaper tiers act, local agents generate.
# "Fable 5 - N" from the design maps to concrete aliases here.
MODEL_TIERS: dict[str, str] = {
    "design": "fable",     # brainstorming / arbitration (judgment)
    "plan": "opus",        # writing-plans
    "execute": "sonnet",   # executing-plans, TDD, running the review panel
    "wrapper": "haiku",    # the local agents' cloud wrapper
}

# Reviewers that feed loop_audit, installed/first-party only. tech-debt / ai-firstify are
# optional add-ons the user enables explicitly.
DEFAULT_REVIEWERS: tuple[str, ...] = (
    "code-review",
    "security-guidance",
    "pr-review-toolkit",
    "systematic-debugging",
)

# An aggregate delta at or below this over the patience window counts as "no progress".
NO_PROGRESS_EPSILON = 0.5


@dataclass
class LoopConfig:
    """Immutable run configuration parsed from the CLI."""

    budget_usd: float
    min_score: float = loop_audit.DEFAULT_MIN_SCORE
    max_iters: int = 10
    no_progress_patience: int = 2
    reviewers: tuple[str, ...] = DEFAULT_REVIEWERS
    allow_merge_pr: bool = True


@dataclass
class Iteration:
    """One recorded loop iteration: its score result and the cloud cost it incurred."""

    index: int
    result: dict[str, Any]  # output of loop_audit.score
    cost_usd: float


@dataclass
class LoopState:
    """Mutable run state: the spend so far and the per-iteration history."""

    history: list[Iteration] = field(default_factory=list)

    @property
    def spent_usd(self) -> float:
        return round(sum(it.cost_usd for it in self.history), 6)

    @property
    def iters_done(self) -> int:
        return len(self.history)

    def best_aggregate(self) -> float:
        return max((it.result["aggregate"] for it in self.history), default=0.0)


def no_progress(state: LoopState, patience: int) -> bool:
    """
    --------------------------------------------------------------------------
    Purpose:
        Detect a plateau: over the last `patience` transitions the aggregate
        score improved by no more than NO_PROGRESS_EPSILON each time.

    Inputs:
        state (LoopState): the run history.
        patience (int): number of recent transitions to require as flat.

    Outputs:
        result (bool): True when the loop is not making meaningful progress.
    --------------------------------------------------------------------------
    """
    # Need patience+1 points to measure `patience` deltas.
    if state.iters_done < patience + 1:
        return False
    recent = state.history[-(patience + 1):]
    deltas = [
        recent[i + 1].result["aggregate"] - recent[i].result["aggregate"]
        for i in range(len(recent) - 1)
    ]
    return all(d <= NO_PROGRESS_EPSILON for d in deltas)


def regressed(state: LoopState) -> bool:
    """
    --------------------------------------------------------------------------
    Purpose:
        Detect a correction that broke the security hard floor or dropped the
        security axis below the previous iteration (a regression that must not
        be carried toward merge).

    Inputs:
        state (LoopState): the run history (needs at least two iterations).

    Outputs:
        result (bool): True when the latest iteration regressed on security.
    --------------------------------------------------------------------------
    """
    if state.iters_done < 2:
        return False
    prev, cur = state.history[-2].result, state.history[-1].result
    if prev["security_floor_ok"] and not cur["security_floor_ok"]:
        return True
    return cur["per_axis"].get("security", 100.0) < prev["per_axis"].get("security", 100.0)


def evaluate_stop(state: LoopState, cfg: LoopConfig) -> tuple[bool, str]:
    """
    --------------------------------------------------------------------------
    Purpose:
        Decide whether the loop should stop after the latest iteration, and why.
        Order: composite gate pass (success) first, then the hard stops.

    Inputs:
        state (LoopState): the run history (latest iteration is the most recent).
        cfg (LoopConfig): thresholds and caps.

    Outputs:
        result (tuple[bool, str]): (stop, reason). `reason` starts with "READY:"
        on a successful gate pass and "STOP:" on a hard stop; empty when not stopping.
    --------------------------------------------------------------------------
    """
    if not state.history:
        return False, ""
    latest = state.history[-1].result

    if latest["gate_pass"]:
        return True, "READY: composite gate passed - awaiting human merge confirmation"
    if state.spent_usd >= cfg.budget_usd:
        return True, f"STOP: budget cap reached (${state.spent_usd} >= ${cfg.budget_usd})"
    if state.iters_done >= cfg.max_iters:
        return True, f"STOP: max iterations reached ({cfg.max_iters})"
    if regressed(state):
        return True, "STOP: security regression vs previous iteration"
    if no_progress(state, cfg.no_progress_patience):
        return True, f"STOP: no progress over {cfg.no_progress_patience} iterations"
    return False, ""


def write_ledger(run_dir: Path, state: LoopState, cfg: LoopConfig, stop_reason: str) -> None:
    """
    --------------------------------------------------------------------------
    Purpose:
        Write the loop-audit-compatible ledger artifacts (loop-run-log.md,
        loop-budget.md, PROCESS.md) reflecting the current run state.

    Inputs:
        run_dir (Path): directory to write the artifacts into.
        state (LoopState): the run history.
        cfg (LoopConfig): the run configuration.
        stop_reason (str): the final stop reason (may be empty mid-run).

    Outputs:
        None. Files are written to run_dir.
    --------------------------------------------------------------------------
    """
    run_dir.mkdir(parents=True, exist_ok=True)

    log_lines = ["# loop-run-log", "", "| iter | aggregate | tests | sec-floor | gate | cost $ |", "|---|---|---|---|---|---|"]
    for it in state.history:
        r = it.result
        log_lines.append(
            f"| {it.index} | {r['aggregate']} | {'ok' if r['tests_green'] else 'red'} "
            f"| {'ok' if r['security_floor_ok'] else 'FAIL'} | {'pass' if r['gate_pass'] else 'fail'} "
            f"| {it.cost_usd} |"
        )
    (run_dir / "loop-run-log.md").write_text("\n".join(log_lines) + "\n", encoding="utf-8")

    budget = [
        "# loop-budget",
        "",
        f"- cap: ${cfg.budget_usd}",
        f"- spent: ${state.spent_usd}",
        f"- remaining: ${round(max(0.0, cfg.budget_usd - state.spent_usd), 6)}",
        f"- iterations: {state.iters_done} / {cfg.max_iters}",
    ]
    (run_dir / "loop-budget.md").write_text("\n".join(budget) + "\n", encoding="utf-8")

    done = bool(stop_reason)
    process = [
        "# PROCESS",
        "",
        f"- [{'x' if state.iters_done else ' '}] loop started",
        f"- [{'x' if state.history and state.history[-1].result['tests_green'] else ' '}] tests green (latest)",
        f"- [{'x' if state.best_aggregate() >= cfg.min_score else ' '}] aggregate >= min_score ({cfg.min_score})",
        f"- [{'x' if state.history and state.history[-1].result['gate_pass'] else ' '}] composite gate passed",
        f"- [ ] human merge confirmation",
        "",
        f"best aggregate: {state.best_aggregate()}",
        f"status: {stop_reason or 'running'}",
    ]
    (run_dir / "PROCESS.md").write_text("\n".join(process) + "\n", encoding="utf-8")


def _run_dry(cfg: LoopConfig, report_paths: list[Path], run_dir: Path, per_iter_cost: float) -> int:
    """
    --------------------------------------------------------------------------
    Purpose:
        Drive the loop-control logic over precomputed report files, with no SDK
        or models. Scores each report, records an iteration, writes the ledger,
        and stops on the same rules as a real run.

    Inputs:
        cfg (LoopConfig): thresholds and caps.
        report_paths (list[Path]): report JSON files, one per simulated iteration.
        run_dir (Path): where to write the ledger artifacts.
        per_iter_cost (float): simulated cloud cost charged per iteration.

    Outputs:
        result (int): 0 if the run ended on a gate pass, 1 on any hard stop or
        exhausting the supplied reports without a pass.
    --------------------------------------------------------------------------
    """
    state = LoopState()
    for i, path in enumerate(report_paths, start=1):
        report = loop_audit.load_report(path)
        result = loop_audit.score(report, min_score=cfg.min_score)
        state.history.append(Iteration(index=i, result=result, cost_usd=per_iter_cost))
        stop, reason = evaluate_stop(state, cfg)
        write_ledger(run_dir, state, cfg, reason if stop else "")
        logger.info("[LOOP] iter %d aggregate=%s gate=%s spent=$%s",
                    i, result["aggregate"], result["gate_pass"], state.spent_usd)
        if stop:
            logger.info("[LOOP] %s", reason)
            return 0 if reason.startswith("READY:") else 1
    logger.info("[LOOP] STOP: reports exhausted without a gate pass")
    write_ledger(run_dir, state, cfg, "STOP: reports exhausted without a gate pass")
    return 1


def _run_loop(cfg: LoopConfig, feature: str, run_dir: Path) -> int:
    """
    --------------------------------------------------------------------------
    Purpose:
        Run the real pipeline through the Claude Agent SDK. Imported lazily so
        the module loads without the SDK; raises a clear error if it is missing.

    Inputs:
        cfg (LoopConfig): thresholds and caps (map to SDK max_budget_usd / max_turns).
        feature (str): the feature request to develop.
        run_dir (Path): where to write the ledger artifacts.

    Outputs:
        result (int): process exit code.

    Notes:
        The SDK wiring (per-stage AgentDefinition with model+effort, the local
        agents driving Ollama over the Bash bridge, the review panel writing a
        report JSON that loop_audit scores) needs a live SDK + Ollama + the review
        plugins to run end to end; that path is validated on the user's machine,
        not in the offline suite. See references/ for the LOOP/STATE templates.
    --------------------------------------------------------------------------
    """
    try:
        import claude_agent_sdk  # noqa: F401
    except ImportError as exc:
        raise SystemExit(
            "[LOOP] claude-agent-sdk is not installed. Install it in this skill's .venv "
            "(pip install -r requirements.txt) and ensure Ollama is running with the local "
            "models, then re-run. Use --dry-run to exercise the control logic offline."
        ) from exc

    # Live pipeline construction happens here on the user's machine. The deterministic
    # control core (scoring, guards, ledger) is shared with --dry-run via evaluate_stop /
    # write_ledger so both paths stop on identical rules.
    raise SystemExit(
        "[LOOP] live SDK run is configured on the target machine; the offline build ships "
        "the control core and --dry-run. Wire the AgentDefinitions per references/LOOP.md, "
        "then remove this guard."
    )


def main(argv: list[str] | None = None) -> int:
    """
    --------------------------------------------------------------------------
    Purpose:
        CLI entry point for the loop driver.

    Inputs:
        argv (list[str] | None): argument vector (defaults to sys.argv[1:]).

    Outputs:
        result (int): process exit code (0 = ended ready-to-merge, 1 = hard stop).
    --------------------------------------------------------------------------
    """
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description="Budget-bounded loop-engineering driver.")
    parser.add_argument("--loop", action="store_true", help="run the real SDK pipeline")
    parser.add_argument("--dry-run", action="store_true", help="drive control logic over report files")
    parser.add_argument("--budget", type=float, required=True, help="hard cost cap in USD")
    parser.add_argument("--score", dest="min_score", type=float, default=loop_audit.DEFAULT_MIN_SCORE)
    parser.add_argument("--max-iters", type=int, default=10)
    parser.add_argument("--patience", type=int, default=2, help="no-progress window")
    parser.add_argument("--feature", type=str, default="", help="feature request (--loop)")
    parser.add_argument("--run-dir", type=Path, default=Path("loop_run"))
    parser.add_argument("--reports", nargs="*", type=Path, default=[], help="report JSONs (--dry-run)")
    parser.add_argument("--dry-cost", type=float, default=0.01, help="simulated cost/iter (--dry-run)")
    parser.add_argument("--no-merge-pr", action="store_true", help="do not open a PR at the merge gate")
    args = parser.parse_args(argv)

    cfg = LoopConfig(
        budget_usd=args.budget,
        min_score=args.min_score,
        max_iters=args.max_iters,
        no_progress_patience=args.patience,
        allow_merge_pr=not args.no_merge_pr,
    )

    if args.dry_run:
        if not args.reports:
            raise SystemExit("[LOOP] --dry-run needs --reports <r1.json> [r2.json ...]")
        return _run_dry(cfg, args.reports, args.run_dir, args.dry_cost)
    if args.loop:
        return _run_loop(cfg, args.feature, args.run_dir)
    raise SystemExit("[LOOP] pass --loop (real run) or --dry-run (control-logic only).")


if __name__ == "__main__":
    sys.exit(main())
